@startuml database

entity school {
  id: TEXT
  --
  name: TEXT
}

entity classroom {
  id: TEXT
  --
  school_id: TEXT
  grade: INTEGER
  name: TEXT
  password_hash: TEXT
}

entity teacher {
  id: TEXT
  --
  class_id: TEXT
  email: TEXT
  password_hash: TEXT
}

entity day_status {
  date: TEXT(date)
  class_id: TEXT
  point: INTEGER
  attend: INTEGER
}

entity sensor_log {
  class_id: TEXT
  time: TEXT(datetime)
  values: TEXT(json)
}

entity checklist {
  student_id(出席番号): TEXT
  class_id: TEXT
  list: TEXT(json)
}

entity class_token {
  token: TEXT
  --
  class_id: TEXT
  expired_time: TEXT(time)
}

entity teacher_token {
  token: TEXT
  --
  teacher_id: TEXT
  expired_time: TEXT(time)
}

entity student_token {
  token: TEXT
  --
  student_id(出席番号): TEXT
  class_id: TEXT
  expired_time: TEXT(time)
}

school ||..|{ classroom
classroom ||..|{ day_status
classroom ||..|{ sensor_log

classroom ||..|{ class_token
teacher ||..|{ teacher_token

@enduml